// Automatically generated by gen.pl, don't edit #	<remove the line>

#define	DNSMASQ_SUPPORT	1
#define	CONFIG_DNSMASQ	y
#define	__CONFIG_DNSMASQ__	1
//#define	LOG_DNSMASQ	0 	<remove the line>
#define	UDHCPD_SUPPORT	1
#define	CONFIG_UDHCPD	y
#define	__CONFIG_UDHCPD__	1
#define	UDHCPC_SUPPORT	1
#define	CONFIG_UDHCPC	y
#define	__CONFIG_UDHCPC__	1
//#define	LOG_DHCPD	0 	<remove the line>
//#define	LOG_DHCPC	0 	<remove the line>
#define	PPPOE_SUPPORT	1
#define	CONFIG_PPPOE	y
#define	__CONFIG_PPPOE__	1
//#define	LOG_PPPOE	0 	<remove the line>
#define	PPTP_SUPPORT	1
#define	CONFIG_PPTP	y
#define	__CONFIG_PPTP__	1
//#define	LOG_PPTP	0 	<remove the line>
#define	L2TP_SUPPORT	1
#define	CONFIG_L2TP	y
#define	__CONFIG_L2TP__	1
//#define	LOG_L2TP	0 	<remove the line>
#define	PPPD_SUPPORT	1
#define	CONFIG_PPPD	y
#define	__CONFIG_PPPD__	1
//#define	LOG_PPPD	0 	<remove the line>
#define	ZEBRA_SUPPORT	1
#define	CONFIG_ZEBRA	y
#define	__CONFIG_ZEBRA__	1
//#define	LOG_ZEBRA	0 	<remove the line>
#define	TFTPD_SUPPORT	1
#define	CONFIG_TFTPD	y
#define	__CONFIG_TFTPD__	1
//#define	LOG_TFTPD	0 	<remove the line>
#define	DDNS_SUPPORT	1
#define	CONFIG_DDNS	y
#define	__CONFIG_DDNS__	1
//#define	LOG_DDNS	0 	<remove the line>
//#define	DDNS3322_SUPPORT	0	<remove the line>
//#define	CONFIG_DDNS3322		<remove the line>
#undef	__CONFIG_DDNS3322__
//#define	LOG_DDNS3322	0 	<remove the line>
//#define	PEANUTHULL_SUPPORT	0	<remove the line>
//#define	CONFIG_PEANUTHULL		<remove the line>
#undef	__CONFIG_PEANUTHULL__
//#define	LOG_PEANUTHULL	0 	<remove the line>
#define	CRON_SUPPORT	1
#define	CONFIG_CRON	y
#define	__CONFIG_CRON__	1
//#define	LOG_CRON	0 	<remove the line>
#define	HTTPD_SUPPORT	1
#define	CONFIG_HTTPD	y
#define	__CONFIG_HTTPD__	1
#define	GET_POST_SUPPORT	1
#define	CONFIG_GET_POST	y
#define	__CONFIG_GET_POST__	1
//#define	LOG_HTTPD	0 	<remove the line>
#define	VLAN_SUPPORT	1
#define	CONFIG_VLAN	y
#define	__CONFIG_VLAN__	1

#if 1
//#define	HSIAB_SUPPORT	0	<remove the line>
//#define	CONFIG_HSIAB		<remove the line>
#undef	__CONFIG_HSIAB__
//#define	LOG_HSIAB	0 	<remove the line>
#define	HEARTBEAT_SUPPORT	1
#define	CONFIG_HEARTBEAT	y
#define	__CONFIG_HEARTBEAT__	1
//#define	LOG_HEARTBEAT	0 	<remove the line>
#define	MULTICAST_SUPPORT	1
#define	CONFIG_MULTICAST	y
#define	__CONFIG_MULTICAST__	1
#define	SETUP_WIZARD_SUPPORT	1
#define	CONFIG_SETUP_WIZARD	y
#define	__CONFIG_SETUP_WIZARD__	1
//#define	PARENTAL_CONTROL_SUPPORT	0	<remove the line>
//#define	CONFIG_PARENTAL_CONTROL		<remove the line>
#undef	__CONFIG_PARENTAL_CONTROL__
//#define	LOG_PARENTAL_CONTROL	0 	<remove the line>
//#define	DDM_SUPPORT	0	<remove the line>
//#define	CONFIG_DDM		<remove the line>
#undef	__CONFIG_DDM__
//#define	LOG_DDM	0 	<remove the line>
#define	HTTPS_SUPPORT	1
#define	CONFIG_HTTPS	y
#define	__CONFIG_HTTPS__	1
#define	EOU_SUPPORT	1
#define	CONFIG_EOU	y
#define	__CONFIG_EOU__	1
//#define	EZC_SUPPORT	0	<remove the line>
//#define	CONFIG_EZC		<remove the line>
#undef	__CONFIG_EZC__
#define	SES_SUPPORT	1
#define	CONFIG_SES	y
#define	__CONFIG_SES__	1
//#define	AOSS_SUPPORT	0	<remove the line>
//#define	CONFIG_AOSS		<remove the line>
#undef	__CONFIG_AOSS__
#define	WRITE_MAC_SUPPORT	1
#define	CONFIG_WRITE_MAC	y
#define	__CONFIG_WRITE_MAC__	1
#define	WRITE_SN_SUPPORT	1
#define	CONFIG_WRITE_SN	y
#define	__CONFIG_WRITE_SN__	1
#define	DIAG_SUPPORT	1
#define	CONFIG_DIAG	y
#define	__CONFIG_DIAG__	1
#endif

//#define	SPEED_BOOSTER_SUPPORT	0	<remove the line>
//#define	CONFIG_SPEED_BOOSTER		<remove the line>
#undef	__CONFIG_SPEED_BOOSTER__
#define	WIRELESS_SUPPORT	1
#define	CONFIG_WIRELESS	y
#define	__CONFIG_WIRELESS__	1
//#define	THROUGHPUT_TEST_SUPPORT	0	<remove the line>
//#define	CONFIG_THROUGHPUT_TEST		<remove the line>
#undef	__CONFIG_THROUGHPUT_TEST__
//#define	MULTIPLE_LOGIN_SUPPORT	0	<remove the line>
//#define	CONFIG_MULTIPLE_LOGIN		<remove the line>
#undef	__CONFIG_MULTIPLE_LOGIN__
//#define	TINYLOGIN_SUPPORT	0	<remove the line>
//#define	CONFIG_TINYLOGIN		<remove the line>
#undef	__CONFIG_TINYLOGIN__
//#define	DNS_SUPPORT	0	<remove the line>
//#define	CONFIG_DNS		<remove the line>
#undef	__CONFIG_DNS__
//#define	VERIZON_LAN_SUPPORT	0	<remove the line>
//#define	CONFIG_VERIZON_LAN		<remove the line>
#undef	__CONFIG_VERIZON_LAN__
//#define	UDHCPD_STATIC_SUPPORT	0	<remove the line>
//#define	CONFIG_UDHCPD_STATIC		<remove the line>
#undef	__CONFIG_UDHCPD_STATIC__
//#define	DHCP_FILTER_SUPPORT	0	<remove the line>
//#define	CONFIG_DHCP_FILTER		<remove the line>
#undef	__CONFIG_DHCP_FILTER__
//#define	ALG_FORWARD_SUPPORT	0	<remove the line>
//#define	CONFIG_ALG_FORWARD		<remove the line>
#undef	__CONFIG_ALG_FORWARD__
//#define	WAN_AUTO_DETECT_SUPPORT	0	<remove the line>
//#define	CONFIG_WAN_AUTO_DETECT		<remove the line>
#undef	__CONFIG_WAN_AUTO_DETECT__
//#define	VERIZON_WAN_SUPPORT	0	<remove the line>
//#define	CONFIG_VERIZON_WAN		<remove the line>
#undef	__CONFIG_VERIZON_WAN__
//#define	UI_REBOOT_SUPPORT	0	<remove the line>
//#define	CONFIG_UI_REBOOT		<remove the line>
#undef	__CONFIG_UI_REBOOT__
//#define	MUST_CHANGE_PWD_SUPPORT	0	<remove the line>
//#define	CONFIG_MUST_CHANGE_PWD		<remove the line>
#undef	__CONFIG_MUST_CHANGE_PWD__
//#define	ARP_TABLE_SUPPORT	0	<remove the line>
//#define	CONFIG_ARP_TABLE		<remove the line>
#undef	__CONFIG_ARP_TABLE__
//#define	PPPOE_RELAY_SUPPORT	0	<remove the line>
//#define	CONFIG_PPPOE_RELAY		<remove the line>
#undef	__CONFIG_PPPOE_RELAY__
//#define	LAN_AUTO_DHCP_SUPPORT	0	<remove the line>
//#define	CONFIG_LAN_AUTO_DHCP		<remove the line>
#undef	__CONFIG_LAN_AUTO_DHCP__
#define	XBOX_SUPPORT	1
#define	CONFIG_XBOX	y
#define	__CONFIG_XBOX__	1

#if 0
#define	MPPPOE_SUPPORT	1
#define	CONFIG_MPPPOE	y
#define	__CONFIG_MPPPOE__	1
//#define	LOG_MPPPOE	0 	<remove the line>
#define	UNNUMBERIP_SUPPORT	1
#define	CONFIG_UNNUMBERIP	y
#define	__CONFIG_UNNUMBERIP__	1
//#define	LOG_UNNUMBERIP	0 	<remove the line>
#endif

//#define	SNMP_SUPPORT	0	<remove the line>
//#define	CONFIG_SNMP		<remove the line>
#undef	__CONFIG_SNMP__
//#define	LOG_SNMP	0 	<remove the line>
//#define	DEBUG_SNMP	0 	<remove the line>
//#define	DEBUG_WEB	0 	<remove the line>
//#define	DEBUG_RC	0 	<remove the line>
//#define	BRCM	0 	<remove the line>
//#define	MY_DEBUG	0 	<remove the line>
//#define	SYSLOG_SUPPORT	0	<remove the line>
//#define	CONFIG_SYSLOG		<remove the line>
#undef	__CONFIG_SYSLOG__
//#define	KLOGD_SUPPORT	0	<remove the line>
//#define	CONFIG_KLOGD		<remove the line>
#undef	__CONFIG_KLOGD__
//#define	WL_WDS_SUPPORT	0	<remove the line>
//#define	CONFIG_WL_WDS		<remove the line>
#undef	__CONFIG_WL_WDS__
//#define	WL_STA_SUPPORT	0	<remove the line>
//#define	CONFIG_WL_STA		<remove the line>
#undef	__CONFIG_WL_STA__
//#define	WAKE_ON_LAN_SUPPORT	0	<remove the line>
//#define	CONFIG_WAKE_ON_LAN		<remove the line>
#undef	__CONFIG_WAKE_ON_LAN__
//#define	SAMBA_SUPPORT	0	<remove the line>
//#define	CONFIG_SAMBA		<remove the line>
#undef	__CONFIG_SAMBA__
#define	BACKUP_RESTORE_SUPPORT	1
#define	CONFIG_BACKUP_RESTORE	y
#define	__CONFIG_BACKUP_RESTORE__	1
//#define	UPNP_FORWARD_SUPPORT	0	<remove the line>
//#define	CONFIG_UPNP_FORWARD		<remove the line>
#undef	__CONFIG_UPNP_FORWARD__
#define	PORT_TRIGGER_SUPPORT	1
#define	CONFIG_PORT_TRIGGER	y
#define	__CONFIG_PORT_TRIGGER__	1
#define	HW_QOS_SUPPORT	1
#define	CONFIG_HW_QOS	y
#define	__CONFIG_HW_QOS__	1
//#define	PERFORMANCE_SUPPORT	0	<remove the line>
//#define	CONFIG_PERFORMANCE		<remove the line>
#undef	__CONFIG_PERFORMANCE__
//#define	PPPOE_SERVER_SUPPORT	0	<remove the line>
//#define	CONFIG_PPPOE_SERVER		<remove the line>
#undef	__CONFIG_PPPOE_SERVER__
//#define	SPECIAL_FORWARD_SUPPORT	0	<remove the line>
//#define	CONFIG_SPECIAL_FORWARD		<remove the line>
#undef	__CONFIG_SPECIAL_FORWARD__
//#define	AOL_SUPPORT	0	<remove the line>
//#define	CONFIG_AOL		<remove the line>
#undef	__CONFIG_AOL__
//#define	EMI_TEST	0 	<remove the line>
//#define	FOR_WAN_PORT	0 	<remove the line>
#define	MULTILANG_SUPPORT	1
#define	CONFIG_MULTILANG	y
#define	__CONFIG_MULTILANG__	1
#define	WEB_UPGRADE_LANGPACK_SUPPORT	1
#define	CONFIG_WEB_UPGRADE_LANGPACK	y
#define	__CONFIG_WEB_UPGRADE_LANGPACK__	1
//#define	DEBUG_MULTILANG	0 	<remove the line>
//#define	WCN_SUPPORT	0	<remove the line>
//#define	CONFIG_WCN		<remove the line>
#undef	__CONFIG_WCN__
#define	SES_BUTTON_SUPPORT	1
#define	CONFIG_SES_BUTTON	y
#define	__CONFIG_SES_BUTTON__	1
//#define	GOOGLE_SUPPORT	0	<remove the line>
//#define	CONFIG_GOOGLE		<remove the line>
#undef	__CONFIG_GOOGLE__
//#define	INTEL_VIIV_SUPPORT	0	<remove the line>
//#define	CONFIG_INTEL_VIIV		<remove the line>
#undef	__CONFIG_INTEL_VIIV__
//#define	RXP_SUPPORT	0	<remove the line>
//#define	CONFIG_RXP		<remove the line>
#undef	__CONFIG_RXP__
//#define	UTELNETD_SUPPORT	0	<remove the line>
//#define	CONFIG_UTELNETD		<remove the line>
#undef	__CONFIG_UTELNETD__
//#define	EBTABLES_SUPPORT	0	<remove the line>
//#define	CONFIG_EBTABLES		<remove the line>
#undef	__CONFIG_EBTABLES__
#define	THREE_ARP_GRATUATOUS_SUPPORT	1
#define	CONFIG_THREE_ARP_GRATUATOUS	y
#define	__CONFIG_THREE_ARP_GRATUATOUS__	1
#define	IGMP_SEND_THE_SECOND_QUERY_PACKET_AFTER_RECEIVE_ONE	1
#define	IGMP_STARTUP_QUERY_INTERVAL	1
#define	IGMP_SEND_THE_SECOND_QUERY_PACKET	1
#define	IGMP_BLOCK_SOME_SPEC_ADDRS	1
#define	IGMP_SEND_V1_QUERIES	1
#define	IGMP_LEAVE_NO_V2_QUERIES_IN_V1_STATE	1
#define	IGMP_FIXED_CDROUTER_ISSUES	1
#define	IGMP_FIXED_TIMER	1
