.TH UCLIBC-READELF 1
.SH NAME
uclibc-readelf \- Displays information about ELF files.
.SH SYNOPSIS
.B uclibc-readelf
[
.B options
]
.SH DESCRIPTION
A small program to display information about ELF files.
.SH BUGS
Maybe.

.SH AUTHORS
Erik Andersen <andersen@codepoet.org>
.br
Manual page written by David Schleef <ds@schleef.org>
.SH SEE ALSO
.BR readelf (1)
