/* This file is automatically generated.
   It defines a symbol `__stub_FUNCTION' for each function
   in the C library which is a stub, meaning it will fail
   every time called, usually setting errno to ENOSYS.  */
#define __stub_chflags
#define __stub_fattach
#define __stub_fchflags
#define __stub_fdetach
#define __stub_fesetexceptflag
#define __stub_fexecve
#define __stub_getcontext
#define __stub_gtty
#define __stub_makecontext
#define __stub_posix_fadvise
#define __stub_posix_fadvise64
#define __stub_revoke
#define __stub_setcontext
#define __stub_setlogin
#define __stub_sigreturn
#define __stub_sstk
#define __stub_stty
#define __stub_swapcontext
