#!/bin/sh
#
# Turn off/on all led for routers RT-N16 and RT-N66U
#
# Version: 0.5 "Sunset"
#
# unlock lan ports and sunset mode by monter[at]techlog.pl

N16=`nvram get t_model_name | grep RT-N16 | wc -l`
N66U=`nvram get t_model_name | grep RT-N66U | wc -l`

if [ "$N16" == "1" -o "$N66U" == "1" ]; then
    case "$1" in
        on)
            /usr/sbin/stealthMode perm_on
            echo "StealthMode Activated"
            logger -t StealthMode Activated
            cru a stealthmode "*/5 * * * * /usr/sbin/stealthMode perm_on"
        ;;
        sun)
            if [ "$2" != "" -a "0$(echo $2|tr -d ' ')" -ge 0 ] ; then
                echo "StealthMode Sunset Enabled"
                logger -t StealthMode Sunset Enabled
                cru a stealthsun_on "0 2 * * * /usr/sbin/stealthMode sun_on $2"
                /usr/sbin/stealthMode sun_on $2
            else
                echo "StealthMode Sunset error - the city code does not specified!"
                logger -p3 -t StealthMode Sunset error - the city code does not specified!
                /usr/sbin/stealthMode
                exit 1
            fi
        ;;
        sun_on)
            ping -q -w 1 -c 1 weather.yahooapis.com > /dev/null
            if [ $? -ne 0 ] ; then
                echo "StealthMode Sunset error - no active Internet connection or weather service unavailable!"
                logger -p3 -t StealthMode Sunset error - no active Internet connection or weather service unavailable!
                /usr/sbin/stealthMode
                exit 1
            else
                if [ "$2" != "" -a "0$(echo $2|tr -d ' ')" -ge 0 ] ; then
                    sun=`l=$2;wget -q -O - http://weather.yahooapis.com/forecastrss?w=$l|grep astronomy| awk -F\" '{print $4}' | awk -F\" '{split($1, A, " ");split(A[1], B, ":");HR=B[1];MIN=B[2];if(A[2] == "pm") HR+=12;$1=sprintf("%d %d", MIN, HR);}1'`
                    if [ "$sun" = "" ] ; then echo "Weather sunset error!"; logger Weather sunset error!; exit 1; else cru a stealthsunset $sun "* * * /usr/sbin/stealthMode on"; fi
                    sur=`l=$2;wget -q -O - http://weather.yahooapis.com/forecastrss?w=$l|grep astronomy| awk -F\" '{print $2}' | awk -F\" '{split($1, A, " ");split(A[1], B, ":");HR=B[1];MIN=B[2];if(A[2] == "pm") HR+=12;$1=sprintf("%d %d", MIN, HR);}1'`
                    if [ "$sur" = "" ] ; then echo "Weather sunrise error!"; logger Weather sunrise error!; exit 1; else cru a stealthsunrise $sur "* * * /usr/sbin/stealthMode off"; fi
                    echo "StealthMode Sunset city code: $2, sunset: $( echo $sun | awk '{ print $2":"$1 }' ), sunrise: $( echo $sur | awk '{ print $2":"$1 }' )"
                    logger -t StealthMode Sunset city code: $2, sunset: $( echo $sun | awk '{ print $2":"$1 }' ), sunrise: $( echo $sur | awk '{ print $2":"$1 }' )
                    HOUR=$(date +%k); SUNRUN=$( echo $sun | awk '{ print $2 }' ); SURRUN=$( echo $sur | awk '{ print $2 }' ); if [ "$HOUR" -ge "$SURRUN" -a "$HOUR" -le "$SUNRUN" ] ; then
                        echo "StealthMode will be activated at next sun set"
                        logger -t StealthMode Service will be activated at next sun set
                    else
                        /usr/sbin/stealthMode on
                    fi
                else
                    echo "StealthMode Sunset error - the city code does not specified!"
                    logger -p3 -t StealthMode Sunset error - the city code does not specified!
                    /usr/sbin/stealthMode
                    exit 1
                fi
            fi
        ;;
        perm_on)
            if [ "$N66U" == "1" ]; then
                wl -i eth2 leddc 1
                gpio enable 12 #power led
                gpio enable 15 #usb led
            else
                gpio enable 1 #power led
                et robord 0x1 0x4 > /dev/null 2>&1 #unlock lan ports
            fi
            et robowr 0x00 0x18 0x1e0
            et robowr 0x00 0x1a 0x1e0
            wl -i eth1 leddc 1
        ;;
        sun_off)
            echo "StealthMode Sunset Disactivated"
            logger -t StealthMode Sunset Disactivated
            cru d stealthsun_on
            cru d stealthsunset
            cru d stealthsunrise
            /usr/sbin/stealthMode off
        ;;
        off)
            if [ "$N66U" == "1" ]; then
                wl -i eth2 leddc 0
                gpio disable 12 #power led
                gpio disable 15 #usb led
            else
                gpio disable 1 #power led
                et robord 0x1 0x4 > /dev/null 2>&1 #unlock lan ports
            fi
            et robowr 0x00 0x18 0x1ff
            et robowr 0x00 0x1a 0x1ff
            wl -i eth1 leddc 0
            echo "StealthMode Disactivated"
            logger -t StealthMode Disactivated
            cru d stealthmode
        ;;
        *)
            echo $"Usage: $0 {on|off|sun <city_code>|sun_off}"
            echo
            echo "  Standard mode"
            echo "    on | off        - enable or disable steathMode in real time"
            echo
            echo "  Sunset mode"
            echo "    sun <city_code> - will daily get the sunrise and sunset times of a specific"
            echo "                      location automatically and activate Sunset mode"
            echo "                      To be able to determine your <city_code> you need to first"
            echo "                      go to http://weather.yahoo.com/ and look up your location"
            echo "                      The last NUMBERS in the URL will be your <city_code>"
            echo "                      This feature requires a working Internet connection"
            echo "    sun_off         - fully deactivate Sunset mode"
            exit 1
    esac
else
    echo "Router is not supported by this feature"
    logger -p1 -t StealthMode Router is not supported by this feature
fi
