#!/bin/sh

#
# Copyright (C) 2011 shibby
#

# is modem ready?

DEV1=`cat /proc/bus/usb/devices | grep Driver | grep option | wc -l`
DEV2=`cat /proc/bus/usb/devices | grep Driver | grep sierra | wc -l`
DEV3=`cat /proc/bus/usb/devices | grep Driver | grep usbserial | wc -l`

if [ "$DEV1" -gt 0 ]; then
    logger 3G MODEM already found - using option module
    nvram set 3g_module=option
    break;
elif [ "$DEV2" -gt 0 ]; then
    logger 3G MODEM already found - using sierra module
    nvram set 3g_module=sierra
    break;
elif [ "$DEV3" -gt 0 ]; then
    logger 3G MODEM already found - using usbserial module
    nvram set 3g_module=usbserial
    break;
else
#modem not found, try detect

DEVICES=`lsusb | awk '{print $6}'`

for SWITCH in $DEVICES; do
SEARCH=`ls /etc/usb_modeswitch.d/$SWITCH | wc -l`

# vendor:product

if [ "$SEARCH" == "1" ]; then
    logger 3G MODEM FOUND - $SWITCH - Switching ...
    usb_modeswitch -c /etc/usb_modeswitch.d/$SWITCH -Q

    TEST1=`cat /etc/usb_modeswitch.d/$SWITCH | grep "TargetVendor" | cut -d "=" -f2 | wc -l`
    if [ "$TEST1" == "1" ]; then
        VENDOR=`cat /etc/usb_modeswitch.d/$SWITCH | grep "TargetVendor" | cut -d "=" -f2`
        VENDOR=`echo $VENDOR | cut -b 3-`
    else
        VENDOR=`echo $SWITCH | cut -d ":" -f1`
    fi

    TEST2=`lsusb | awk '{print $6}' | grep $VENDOR | wc -l`
    if [ "$TEST2" == "1" ]; then
        PRODUCT=`lsusb | awk '{print $6}' | grep $VENDOR | cut -d ":" -f2`
        logger 3G MODEM ready - $VENDOR:$PRODUCT
        echo "$VENDOR:$PRODUCT" > /tmp/3g.detect
        nvram set 3g_module=usbserial
    fi
fi
done

#trying option and sierra module first
modprobe option
modprobe sierra
sleep 2
DEV=`cat /proc/bus/usb/devices | grep Driver | grep option | wc -l`
DEV2=`cat /proc/bus/usb/devices | grep Driver | grep sierra | wc -l`
if [ "$DEV" -gt 0 ]; then
    logger 3G MODEM ready - using option module
    nvram set 3g_module=option
    break;
elif [ "$DEV2" -gt 0 ]; then
    logger 3G MODEM ready - using sierra module
    nvram set 3g_module=sierra
    break;
else
    logger 3G MODEM not found by option and sierra module. Trying usbserial ...

    rmmod sierra
    rmmod option

    if [ -z $VENDOR ]; then
        if [ -z $PRODUCT ]; then
            logger 3G MODEM - loading module usbserial
            rmmod usbserial
            insmod usbserial vendor=0x$VENDOR product=0x$PRODUCT maxSize=4096
        fi
    fi

    DEV=`cat /proc/bus/usb/devices | grep Driver | grep usbserial | wc -l`
    if [ "$DEV" -gt 0 ]; then
        logger 3G MODEM ready - using usbserial module
        nvram set 3g_module=usbserial
        break;
    elif [ -f /tmp/3g.detect ]; then
        VENDOR=`cat /tmp/3g.detect | cut -d ":" -f1`
        PRODUCT=`cat /tmp/3g.detect | cut -d ":" -f2`
        TEST3=`lsusb | grep $VENDOR | grep $PRODUCT | wc -l`
        if [ "$TEST3" == "1" ]; then
            logger 3G MODEM FOUND - already switched - Last know $VENDOR:$PRODUCT

            DEV=`cat /proc/bus/usb/devices | grep Driver | grep usbserial | wc -l`
            if [ "$DEV" -gt 0 ]; then
                logger 3G MODEM ready - using usbserial module
                nvram set 3g_module=usbserial
                break;
            else
                logger 3G MODEM - loading module
                rmmod usbserial
                insmod usbserial vendor=0x$VENDOR product=0x$PRODUCT maxSize=4096
                nvram set 3g_module=usbserial
                break;
            fi
        fi
    else
        #last change. try load usbserial for each usb devices
        DEVICES=`lsusb | awk '{print $6}'`
        for SWITCH in $DEVICES; do
            VENDOR=`echo $SWITCH | cut -d ":" -f1`
            PRODUCT=`echo $SWITCH | cut -d ":" -f2`
                rmmod usbserial
                insmod usbserial vendor=0x$VENDOR product=0x$PRODUCT maxSize=4096

                DEV=`cat /proc/bus/usb/devices | grep Driver | grep usbserial | wc -l`
                if [ "$DEV" -gt 0 ]; then
                    logger 3G MODEM ready - using usbserial module
                    nvram set 3g_module=usbserial
                    NO=0
                    break;
                else
                    NO=1
                fi
        done
    fi
fi

fi

if [ "$NO" == "1" ]; then
    logger 3G MODEM not found ... sorry
fi
