#!/bin/sh

COUNT=0

DEVICES=`lsusb | awk '{print $6}'`

for SWITCH in $DEVICES; do
SEARCH=`ls /etc/usb_modeswitch.d/$SWITCH | wc -l`

# vendor:product

if [ "$SEARCH" == "1" ]; then
    logger 3G MODEM FOUND - $SWITCH - Switching ...
    usb_modeswitch -c /etc/usb_modeswitch.d/$SWITCH

    TEST1=`cat /etc/usb_modeswitch.d/$SWITCH | grep "TargetVendor" | cut -d "=" -f2 | wc -l`
    if [ "$TEST1" == "1" ]; then
        VENDOR=`cat /etc/usb_modeswitch.d/$SWITCH | grep "TargetVendor" | cut -d "=" -f2`
        VENDOR=`echo $VENDOR | cut -b 3-`
    else
        VENDOR=`echo $SWITCH | cut -d ":" -f1`
    fi

    TEST2=`lsusb | awk '{print $6}' | grep $VENDOR | wc -l`
    if [ "$TEST2" == "1" ]; then
        PRODUCT=`lsusb | awk '{print $6}' | grep $VENDOR | cut -d ":" -f2`
        logger 3G MODEM ready - $VENDOR:$PRODUCT
        nvram set usb_3g_know="$VENDOR:$PRODUCT" # save last know modem
        nvram commit

        DEV0=`ls /dev/ttyUSB0 | wc -l`
        if [ "$DEV0" == "1" ]; then
            logger 3G MODEM ready - ttyUSB0 exists
            break;
        else
            logger 3G MODEM - loading module
            rmmod usbserial
            insmod usbserial vendor=0x$VENDOR product=0x$PRODUCT maxSize=4096
            break;
        fi
    else
        logger 3G MODEM error - something is wrong - check $VENDOR:$PRODUCT ...
    fi
else
    #try last know modem info
    VENDOR=`nvram get usb_3g_know | cut -d ":" -f1`
    PRODUCT=`nvram get usb_3g_know | cut -d ":" -f2`
    TEST3=`lsusb | grep $VENDOR | grep $PRODUCT | wc -l`
    if [ "$TEST3" == "1" ]; then
        logger FOUND 3G MODEM already switched - Last know  $VENDOR:$PRODUCT

        DEV0=`ls /dev/ttyUSB0 | wc -l`
        if [ "$DEV0" == "1" ]; then
            logger 3G MODEM ready - ttyUSB0 exists
            break;
        else
            logger 3G MODEM - loading module
            rmmod usbserial
            insmod usbserial vendor=0x$VENDOR product=0x$PRODUCT maxSize=4096
            break;
        fi
    else
        COUNT=1
    fi
fi

done

if [ "$COUNT" == "1" ]; then
logger 3G MODEM not found ... sorry
fi