#!/bin/sh

###############################
# Copyright (C) 2012 shibby
#
# This script send anonymous or incompleted information about model of router and installed tomato version.
# Those information will be used ONLY for stats.
# Any of private information will be NOT sended!
# Results you can explore on http://tomato.groov.pl/tomatoanon.php page.
# If you don`t agree to run this script you can set nvram variable tomatoanon to 0.
#
# Sended information:
# - MD5SUM of WAN+LAN MAC addresses - this will identify a router. Ex: 1c1dbd4202d794251ec1acf1211bb2c8
# - Model of router. Ex: Asus RT-N66U
# - Version of installed tomato. Ex: 102 K26 USB
# - Builtype. Ex: Mega-VPN-64K
# - Country. Ex: POLAND
# - ISO Country code. Ex: PL
# - Uptime of your router. Ex: 3 days
#
# That`s all
###############################

ANON_ENABLED=`nvram get tomatoanon_enable`
ANON_ANSWER=`nvram get tomatoanon_answer`

if [ "$ANON_ANSWER" == "1" ]; then
    if [ "$ANON_ENABLED" == "1" ]; then

        #Collect datas
        MOD=Shibby
        UPTIME=`uptime | cut -d "," -f1 | cut -d " " -f4,5`
        WANMAC=`nvram get wan_hwaddr`
        LANMAC=`nvram get lan_hwaddr`
        MODEL=`nvram get t_model_name`
        DRIVER=`wl ver | grep version | awk '{ print $7 }'`
        WANMAC_MD5=`echo "$WANMAC+$LANMAC" | md5sum | awk '{ print $1 }'`

        ROUTERID=`nvram get tomatoanon_id`
        if [ ! "$ROUTERID" == "$WANMAC_MD5" ]; then
            nvram set tomatoanon_id="$WANMAC_MD5"
            nvram commit
        fi

        #Detect Version and Buildtype
        KERNEL=`uname -r | cut -d "." -f1,2`
        if [ "$KERNEL" == "2.6" ]; then
            IS_USB=`nvram get os_version | grep USB | wc -l`
            if [ "$IS_USB" == "0" ]; then #if K26
                VER=`nvram get os_version | awk '{ print $2" "$3 }' | cut -d "-" -f2`
                BUILDTYPE=`nvram get os_version | awk '{ print $4 }'`
            else #if K26USB
                VER=`nvram get os_version | awk '{ print $2" "$3" "$4 }' | cut -d "-" -f2`
                BUILDTYPE=`nvram get os_version | awk '{ print $5 }'`
            fi
        else #K2.4
            IS_USB=`nvram get os_version | grep USB | wc -l`
            if [ "$IS_USB" == "0" ]; then #if K24
                VER=`nvram get os_version | awk '{ print $2" "$3 }'`
                BUILDTYPE=`nvram get os_version  |  awk '{ print $4 }'`
            else # if K24USB
                VER=`nvram get os_version | awk '{ print $2" "$3" "$4 }'`
                BUILDTYPE=`nvram get os_version | awk '{ print $5 }'`
            fi
        fi

        #Get country name and code
        wget -O /tmp/country http://api.easyjquery.com/test/demo-ip.php
        ISO=`cat /tmp/country | grep Country] | awk '{ print $3 }'`
        COUNTRY=`cat /tmp/country | grep CountryName | awk '{ print $3" "$4" "$5 }'`
        rm /tmp/country

        #Change all spaces to %20.
        echo "http://tomato.groov.pl/tomatoanon.php?wanmac_md5=$WANMAC_MD5&model=$MODEL&version=$VER&buildtype=$BUILDTYPE&country=$COUNTRY&flag=$ISO&driver=$DRIVER&uptime=$UPTIME&mod=$MOD&anon=1" > /tmp/AnonLink
        sed -i "s/ /%20/g" /tmp/AnonLink
        ANONSEND=`cat /tmp/AnonLink`
        rm /tmp/AnonLink

        #We have all we need well we can send datas to Anon database
        wget -O /dev/null $ANONSEND

        #Thanks

        INTERVAL=`nvram get tomatoanon_cru`
        cru d tomatoanon
        cru a tomatoanon "0 */$INTERVAL * * * /usr/sbin/tomatoanon"

    else #if anon is not enabled or was disabled right now

        ISCRU=`cru l | grep tomatoanon | wc -l`
        if [ "$ISCRU" == "0" ]; then
            cru d tomatoanon
        fi

    fi #end ANON_ENABLE

else #if answer is not enabled or was disabled right now

    ISCRU=`cru l | grep tomatoanon | wc -l`
    if [ "$ISCRU" == "0" ]; then
        cru d tomatoanon
    fi

fi #end ANON_ANSWER
