#!/bin/sh

#
# Copyright (C) 2015 shibby
#

PREFIX=$1
MWAN=`nvram get mwan_num`
IFACE=`nvram get "$PREFIX"_ifname`
PROTO=`nvram get "$PREFIX"_proto`
WEIGHT=`nvram get "$PREFIX"_weight`
ADDR=`ifconfig "$IFACE" | grep inet | cut -d ":" -f2 | cut -d " " -f1`
LOCK="/tmp/watchdog.$PREFIX"
MTD=`nvram get mwan_ckmtd`
DST=`nvram get mwan_ckdst`
HOSTLIST=`echo $DST |  sed 's/,/ /'`
RESULT=0

cktracert() {
    RXBYTES1=`cat /sys/class/net/$IFACE/statistics/rx_bytes`
    for HOST in $HOSTLIST; do
        # we need only send/receive few packages to be sure is connection works.
        # Probe = 1, Max hops = 3
        traceroute -i $IFACE -w 1 -m 3 $HOST > /dev/null 2>&1
    done
    RXBYTES2=`cat /sys/class/net/$IFACE/statistics/rx_bytes`
    if [ "$RXBYTES2" -gt "$RXBYTES1" ]; then
        RESULT=1
    fi
}

ckping() {
    OK=0

    for HOST in $HOSTLIST; do
        TEST=`ping -I $IFACE -c 4 $HOST | grep "received" | cut -d "," -f2 | cut -d " " -f2`

        if [ "$TEST" -gt "0" ]; then  # "0" means 100% loss - not receive any package
            OK=`expr $OK + 1`
        fi
    done

    if [ "$OK" -gt "0" ]; then
        RESULT=1
    fi
}

ckfailover() {
    TEST=`ip route | grep $IFACE | wc -l`

    if [ "$TEST" -gt "0" ]; then
        RESULT=1
    fi
}

watchdogRun() {

    if [ "$PREFIX" == "wan" ]; then
        METRIC="101"
    else
        PREFNR=`echo "$PREFIX" | cut -c 4-`
        METRIC=`expr $PREFNR + 100`
    fi

    ADD=0
    ISGW=`ip route | grep $IFACE | grep -v "link" | wc -l`
    if [ "$ISGW" == "0" -a "$WEIGHT" > "0" ]; then
        #failback required default gateway to check is indeed connection back to live
        #so we have to add temporary gateway
        GW=`ip route | grep $IFACE | grep -v "kernel" | awk {' printf $1'}`
        if [ -n "$GW" -a ! "$GW" == "0.0.0.0" ]; then
            route add default gw $GW metric $METRIC
            ADD=1
        fi
    fi

    if [ "$MTD" == "1" ]; then
        ckping
    else
        cktracert
    fi

    #remove temporary added gateway
    if [ "$ADD" == "1" ]; then
        route del default gw $GW
    fi

    if [ "$RESULT" == "0" -a "$WEIGHT" == "0" ]; then
        #failover does not have default gateway in route table
        #so we can`t check connection to outsite. Check only is interface exist
        ckfailover
    fi

    if [ "$RESULT" == "0" ]; then
        logger WAN Watchdog - Connection $PREFIX down - Reconnecting ...
        echo "0" > /tmp/"$PREFIX"_state

        if [ "$PROTO" == "lte" ]; then
            switch4g $PREFIX
        else
            if [ "$PREFIX" == "wan" ]; then
                if [ "$MWAN" == "1" ]; then
                    service wan restart
                else
                    service wan1 restart
                fi
            else
                service $PREFIX restart
            fi
        fi

    else
        echo "1" > /tmp/"$PREFIX"_state
    fi
}

watchdogAdd() {
    CKTIME=`nvram get mwan_cktime`
    MINS=`expr "$CKTIME" / 60`

    if [ "$MINS" -gt 0 ]; then
        ISSET=`cru l | grep watchdog_"$PREFIX" | wc -l`

        if [ "$ISSET" == "0" ]; then
            cru a watchdog_$PREFIX "*/$MINS * * * * /usr/sbin/watchdog $PREFIX"
        fi
    fi
    echo "1" > /tmp/"$PREFIX"_state
}

watchdogDel() {
    ISSET=`cru l | grep watchdog_"$PREFIX" | wc -l`

    if [ "$ISSET" == "1" ]; then
        cru d watchdog_"$PREFIX"
    fi
}

checkLock() {
    if [ -f $LOCK ]; then #lock exist
        logger WAN Watchdog - another proces in action for $PREFIX
        exit 0
    fi

    touch $LOCK
}

checkLock2() {
    if [ -f /etc/switch3g.lock -o -f /etc/switch4g.lock ]; then
        logger WAN Watchdog - switch3g or switch4g script in action for $PREFIX - skip
        rm $LOCK
        exit 0
    fi
}

###################################################

checkLock

checkLock2

if [ -n "$1" ]; then
    if [ "$2" == "add" ]; then
        watchdogAdd
    elif [ "$2" == "del" ]; then
        watchdogDel
    else
        watchdogRun
    fi
fi

rm $LOCK
