/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* BSDI */
/* #undef BSDI_NRL */

/* Disable BGP installation to zebra */
/* #undef DISABLE_BGP_ANNOUNCE */

/* FreeBSD 3.2 */
/* #undef FREEBSD_32 */

/* GNU Linux */
#define GNU_LINUX 

/* Define to 1 if you have the <asm/types.h> header file. */
#define HAVE_ASM_TYPES_H 1

/* Define to 1 if you have the `bcopy' function. */
#define HAVE_BCOPY 1

/* Broken Alias */
/* #undef HAVE_BROKEN_ALIASES */

/* Define to 1 if you have the `bzero' function. */
#define HAVE_BZERO 1

/* Define to 1 if you have the `daemon' function. */
#define HAVE_DAEMON 1

/* Define to 1 if you have the `getaddrinfo' function. */
#define HAVE_GETADDRINFO 1

/* Define to 1 if you have the `getifaddrs' function. */
/* #undef HAVE_GETIFADDRS */

/* GNU regexp library */
#define HAVE_GNU_REGEX 

/* ifaliasreq */
/* #undef HAVE_IFALIASREQ */

/* Define to 1 if you have the `if_indextoname' function. */
#define HAVE_IF_INDEXTONAME 1

/* Define to 1 if you have the `if_nametoindex' function. */
#define HAVE_IF_NAMETOINDEX 1

/* in6addr global variables e.g. in6addr_loopback */
#define HAVE_IN6ADDR_GLOBAL 

/* in6_aliasreq */
/* #undef HAVE_IN6_ALIASREQ */

/* Define to 1 if you have the `inet_aton' function. */
#define HAVE_INET_ATON 1

/* Define to 1 if you have the <inet/nd.h> header file. */
/* #undef HAVE_INET_ND_H */

/* inet_ntop */
#define HAVE_INET_NTOP 

/* inet_pton */
#define HAVE_INET_PTON 

/* in_pktinfo */
#define HAVE_INPKTINFO 

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* IPv6 */
#define HAVE_IPV6 1

/* IRDP */
/* #undef HAVE_IRDP */

/* Define to 1 if you have the <kvm.h> header file. */
/* #undef HAVE_KVM_H */

/* Define to 1 if you have the `crypt' library (-lcrypt). */
#define HAVE_LIBCRYPT 1

/* Define to 1 if you have the `kvm' library (-lkvm). */
/* #undef HAVE_LIBKVM */

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the `ncurses' library (-lncurses). */
/* #undef HAVE_LIBNCURSES */

/* Define to 1 if you have the `nsl' library (-lnsl). */
/* #undef HAVE_LIBNSL */

/* Define to 1 if you have the `readline' library (-lreadline). */
/* #undef HAVE_LIBREADLINE */

/* Define to 1 if you have the `resolv' library (-lresolv). */
/* #undef HAVE_LIBRESOLV */

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define to 1 if you have the `termcap' library (-ltermcap). */
/* #undef HAVE_LIBTERMCAP */

/* Define to 1 if you have the `tinfo' library (-ltinfo). */
/* #undef HAVE_LIBTINFO */

/* Define to 1 if you have the <libutil.h> header file. */
/* #undef HAVE_LIBUTIL_H */

/* Define to 1 if you have the `xnet' library (-lxnet). */
/* #undef HAVE_LIBXNET */

/* Linux TCP Signature Option */
/* #undef HAVE_LINUX_TCP_SIGNATURE */

/* Define to 1 if you have the <linux/version.h> header file. */
#define HAVE_LINUX_VERSION_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet6/nd6.h> header file. */
/* #undef HAVE_NETINET6_ND6_H */

/* Define to 1 if you have the <netinet/icmp6.h> header file. */
#define HAVE_NETINET_ICMP6_H 1

/* Define to 1 if you have the <netinet/in6.h> header file. */
/* #undef HAVE_NETINET_IN6_H */

/* Define to 1 if you have the <netinet/in6_var.h> header file. */
/* #undef HAVE_NETINET_IN6_VAR_H */

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the <netinet/in_var.h> header file. */
/* #undef HAVE_NETINET_IN_VAR_H */

/* netlink */
#define HAVE_NETLINK 

/* NET-SNMP */
/* #undef HAVE_NETSNMP */

/* Define to 1 if you have the <net/if_dl.h> header file. */
/* #undef HAVE_NET_IF_DL_H */

/* Define to 1 if you have the <net/if_var.h> header file. */
/* #undef HAVE_NET_IF_VAR_H */

/* Define to 1 if you have the <net/netopt.h> header file. */
/* #undef HAVE_NET_NETOPT_H */

/* NET_RT_IFLIST */
/* #undef HAVE_NET_RT_IFLIST */

/* OSPF NSSA */
/* #undef HAVE_NSSA */

/* OSPF Opaque LSA */
/* #undef HAVE_OPAQUE_LSA */

/* OpenBSD TCP Signature Option */
/* #undef HAVE_OPENBSD_TCP_SIGNATURE */

/* OSPF TE */
/* #undef HAVE_OSPF_TE */

/* /proc/net/dev */
#define HAVE_PROC_NET_DEV 

/* /proc/net/if_inet6 */
#define HAVE_PROC_NET_IF_INET6 

/* rt_addrinfo */
/* #undef HAVE_RT_ADDRINFO */

/* rusage */
#define HAVE_RUSAGE 

/* sa_len */
/* #undef HAVE_SA_LEN */

/* Define to 1 if you have the `setproctitle' function. */
/* #undef HAVE_SETPROCTITLE */

/* scope id */
#define HAVE_SIN6_SCOPE_ID 

/* sin_len */
/* #undef HAVE_SIN_LEN */

/* SNMP */
/* #undef HAVE_SNMP */

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* sockaddr_dl */
/* #undef HAVE_SOCKADDR_DL */

/* socklen_t */
#define HAVE_SOCKLEN_T 

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strlcat' function. */
#define HAVE_STRLCAT 1

/* Define to 1 if you have the `strlcpy' function. */
#define HAVE_STRLCPY 1

/* Define to 1 if you have the <stropts.h> header file. */
/* #undef HAVE_STROPTS_H */

/* sun_len */
/* #undef HAVE_SUN_LEN */

/* Define to 1 if you have the <sys/conf.h> header file. */
/* #undef HAVE_SYS_CONF_H */

/* Define to 1 if you have the <sys/ksym.h> header file. */
/* #undef HAVE_SYS_KSYM_H */

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/sockio.h> header file. */
/* #undef HAVE_SYS_SOCKIO_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/sysctl.h> header file. */
#define HAVE_SYS_SYSCTL_H 1

/* Define to 1 if you have the <sys/times.h> header file. */
#define HAVE_SYS_TIMES_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* TCP Signature Option */
/* #undef HAVE_TCP_SIGNATURE */

/* Use TCP for zebra communication */
/* #undef HAVE_TCP_ZEBRA */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Inria IPv6 */
/* #undef INRIA_IPV6 */

/* KAME IPv6 */
/* #undef KAME */

/* Linux IPv6 */
#define LINUX_IPV6 

/* NRL */
/* #undef NRL */

/* OpenBSD */
/* #undef OPEN_BSD */

/* Name of package */
#define PACKAGE "zebra"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* bgpd PID */
#define PATH_BGPD_PID "/var/run/bgpd.pid"

/* ospf6d PID */
#define PATH_OSPF6D_PID "/var/run/ospf6d.pid"

/* ospfd PID */
#define PATH_OSPFD_PID "/var/run/ospfd.pid"

/* ripd PID */
#define PATH_RIPD_PID "/var/run/ripd.pid"

/* ripngd PID */
#define PATH_RIPNGD_PID "/var/run/ripngd.pid"

/* zebra PID */
#define PATH_ZEBRA_PID "/var/run/zebra.pid"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* SunOS 5 */
/* #undef SUNOS_5 */

/* Use PAM for authentication */
/* #undef USE_PAM */

/* Version number of package */
#define VERSION "0.95"

/* VTY shell */
/* #undef VTYSH */

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define to 1 if on AIX 3.
   System headers sometimes define this.
   We just want to avoid a redefinition error message.  */
#ifndef _ALL_SOURCE
/* # undef _ALL_SOURCE */
#endif

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */
