language: c
compiler:
  - gcc

script: 
  - autoconf && autoheader && ./configure $BUNDLEDLIBTOM CFLAGS="-O2 -Wall -Wno-pointer-sign $WEXTRAFLAGS" --prefix=$HOME/inst 
  - test "$NOWRITEV" && sed -i s/HAVE_WRITEV/DONT_HAVE_WRITEV/ config.h || true
  - make install
  - ~/inst/bin/dropbearkey -t rsa -f testrsa
  - ~/inst/bin/dropbearkey -t dss -f testdss
  - ~/inst/bin/dropbearkey -t ecdsa -f testec256 -s 256
  - ~/inst/bin/dropbearkey -t ecdsa -f testec384 -s 384
  - ~/inst/bin/dropbearkey -t ecdsa -f testec521 -s 521

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libz-dev libtomcrypt-dev libtommath-dev

env: 
  - BUNDLEDLIBTOM=--disable-bundled-libtom WEXTRAFLAGS=-Werror
  - BUNDLEDLIBTOM=--enable-bundled-libtom
  - MULTI=1
  - NOWRITEV=1
