# $Id: Makefile,v 1.1.1.4 2003/10/14 08:07:51 sparq Exp $
# Makefile for the linux Sparc64-specific parts of the memory manager.
#

USE_STANDARD_AS_RULE := true
EXTRA_AFLAGS := -ansi

O_TARGET := mm.o
obj-y    := ultra.o fault.o init.o generic.o extable.o modutil.o

include $(TOPDIR)/Rules.make
