export LINUXDIR := $(SRCBASE)/linux/linux-2.6

EXTRA_CFLAGS := -DLINUX26 -DCONFIG_BCMWL5 -DCONFIG_BCMWL6 -DCONFIG_BCMWL6A -DCONFIG_BCM7 -DPART_JFFS2_GAP=0UL -pipe -fno-strict-aliasing

export CONFIG_LINUX26=y
export CONFIG_BCMWL5=y
export CONFIG_BCMWL6=y
export CONFIG_BCMWL6A=y
export CONFIG_BCM7=y
export TOMATO_EXPERIMENTAL=0
