#!/bin/sh
TOP=/raid1/tomato/tomato.git/release.ar.wp/src-rt/router
CONFIGURE="./configure"
CC=mipsel-linux-gcc
CXX=mipsel-linux-gcc

CC=$CC CXX=$CXX STRIP='mipsel-uclibc-strip' \
	CFLAGS="-O2 -Wall -fno-delete-null-pointer-checks -funit-at-a-time \
	--param large-function-growth=800 --param max-inline-insns-single=3000 \
	-ffunction-sections -fdata-sections" \
	LDFLAGS="-L$TOP/libstdc++/prebuilt" \
	LIBS="-lstdc++" \
	$CONFIGURE --host=mipsel-linux --build=x86_64-linux-gnu --target=mipsel-linux --prefix=/usr --with-shared --with-normal --disable-debug --without-ada --without-manpages --without-progs --without-tests --enable-termcap

make DESTDIR=$TOP/libncurses/staged install
