
<font color="#0000ff" size=+2><b>General</b></font><br>
<a href="index.html">Apcupsd Home</a><br>
<a href="http://sourceforge.net/project/stats/detail.php?group_id=54413&ugn=apcupsd&type=prweb">Site Visits</a><br>

&nbsp;<br>
<font color="#0000ff" size=+2><b>Documentation</b></font><br>
<a href="manual/manual.html">Online Manual</a><br>
<a href="manual/manual.pdf">PDF Manual</a><br>

&nbsp;<br>
<font color="#0000ff" size=+2><b>Downloads</b></font><br>
<a href="http://prdownloads.sourceforge.net/apcupsd">All Files</a><br>

&nbsp;<br>
<font color="#0000ff" size=+2><b>Support</b></font><br>
<a href="lists.html">Email Lists</a><br>
<a href="support.html">Support</a><br>
<a href="bugs.html">Bug Reporting</a><br>

&nbsp;<br>
<font color="#0000ff" size=+2><b>SourceForge</b></font><br>
<a href="http://sourceforge.net/projects/apcupsd">Project Page</a><br>
<a href="http://sourceforge.net/cvs/?group_id=54413">CVS</a><br>
