##
##

#use wml::std::page
#use wml::des::space
#use wml::des::typography
#use wml::std::box

<page 
   title="Apcupsd, a daemon for controlling APC UPSes"       
   bgcolor="#ffffff"
   indent=0.01
>

<head>
<meta name="Description" content="Apcupsd a monitoring daemon for APC UPSes">
<meta name="Keywords" content="Apcupsd, APC, UPS, UNIX, monitor">
<meta name="Copyright" content="Copyright (C) 1999-2005 Kern Sibbald">
##<link rel="stylesheet" href="apcupsd-styles.css" type="text/css">
</head>

<div align="center">
 <img src="apcupsd.gif" ALT="Apcupsd" height="64" width="584">
</div>

<table height=100% border="0" cellspacing="0" cellpading="4">
<tr> <td width=12% bgcolor="#ffffff" valign="top">
#include "menu.inc"
<p>
<a href="http://sourceforge.net/projects/apcupsd">
<img src="http://sflogo.sourceforge.net/sflogo.php?group_id=54413&type=11" border="0" width="120" height="30" alt="SourceForge.net Logo"/>
</a>
</td>
<td bgcolor="#ffffff"><font size="1">&nbsp;&nbsp;&nbsp;&nbsp;</font></td>
<td bgcolor="#ffffff" valign="top">
{#BODY#}
</td>
</tr>
</table>
{#BODY#:
